import { Outfit } from "next/font/google";
import "./globals.css";
import ConvextClientProvider from "./ConvextClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className}>
        <ConvextClientProvider>{children}</ConvextClientProvider>
      </body>
    </html>
  );
}
